version: '3.8'
services:
    postgres:
        image: postgres
        restart: on-failure   
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - POSTGRES_HOST_AUTH_METHOD=trust
               
    scheduler:
        image: zephyr168/airflow:3.0
        command: scheduler
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./vocab_model:/opt/airflow/vocab_model
    webserver:
        image: zephyr168/airflow:3.0
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env  
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./vocab_model:/opt/airflow/vocab_model
        ports:
            - "8080:8080"