version: '3.8'
services:
    postgres:
        image: postgres
        restart: on-failure   
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - POSTGRES_HOST_AUTH_METHOD=trust
            
    database:
        image: mongo
        ports:
            - '27017:27017'
        volumes: 
            - ./data_new:/data/db
        
    scheduler:
        image: zephyr168/airflow:3.0
        command: scheduler
        restart: always
        depends_on:
            - postgres
            - database
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./posts:/opt/airflow/posts
            - ./weight_vocab:/opt/airflow/weight_vocab
    webserver:
        image: zephyr168/airflow:3.0
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
            - database
        env_file:
            - .env  
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./posts:/opt/airflow/posts
            - ./weight_vocab:/opt/airflow/weight_vocab
        ports:
            - "8080:8080"